MODEL:
  META_ARCHITECTURE: VLMRCNN
  MASK_ON: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: build_timm_fpn_backbone
  TIMM:
    BASE_NAME: resnet50
    PRETRAINED: True
    FREEZE_AT: 2
    OUT_LEVELS: [2, 3, 4, 5]
  FPN:
    IN_FEATURES: ["layer2", "layer3", "layer4", "layer5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: 'VLMROIHeads'
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 80
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
    NUM_FC: 2
    MULT_OBJECT_SCORE: True
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_DIM: 1024
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_RN50_a+cname.npy'
    ZEROSHOT_WEIGHT_INFERENCE_PATH: 'datasets/metadata/coco_clip_RN50_a+cname.npy'
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_MASK: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
DATALOADER:
  NUM_WORKERS: 4
VERSION: 2
OUTPUT_DIR: "output/VLPart/auto"
