_BASE_: "../coco/r50_coco.yaml"
MODEL:
  WEIGHTS: 'models/r50_pascalpart.pth'
  ROI_HEADS:
    NUM_CLASSES: 93 # max of num_classes in all train datasets
  ROI_BOX_HEAD:
    MULT_OBJECT_SCORE: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    USE_ZEROSHOT_CLS_GROUP: True
    ZEROSHOT_WEIGHT_DIM: 1024
    ZEROSHOT_WEIGHT_PATH_GROUP: [
      'datasets/metadata/pascal_part_clip_RN50_a+cname.npy',
      'datasets/metadata/partimagenet_supercat_clip_RN50_a+cname.npy',
      'datasets/metadata/partimagenet_clip_RN50_a+cname.npy'
    ]
    ZEROSHOT_WEIGHT_INFERENCE_PATH: 'datasets/metadata/partimagenet_clip_RN50_a+cname.npy'
    IGNORE_ZERO_CATS_GROUP: [False, False, False]
    USE_FED_LOSS_GROUP: [False, False, False]
    NOUNS_LOSS_WEIGHT: 0.1
    PARSED_PART_LOSS_WEIGHT: 0.1
DATASETS:
  TRAIN: ("pascal_part_train", "partimagenet_supercat", "partimagenet_parsed")
  TEST: ("partimagenet_val",)
SOLVER:
  IMS_PER_BATCH: 16
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005
  STEPS: (20000, 25000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 5000
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (640, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 1, 1]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 8, 4]
  USE_RFS: [False, False, False]
  DATASET_MIN_SIZES: [[640, 800], [400, 400], [640, 800]]
  DATASET_MAX_SIZES: [1333, 667, 1333]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['part', 'image', 'ppart']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True