_BASE_: "../coco/swinbase_cascade_coco.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1203 # max of num_classes in all train datasets
  ROI_BOX_HEAD:
    MULT_OBJECT_SCORE: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    USE_ZEROSHOT_CLS_GROUP: True
    ZEROSHOT_WEIGHT_DIM: 1024
    ZEROSHOT_WEIGHT_PATH_GROUP: [
      'datasets/metadata/lvis_v1_clip_RN50_a+cname.npy',
      'datasets/metadata/paco_clip_RN50_a+cname.npy',
    ]
    ZEROSHOT_WEIGHT_INFERENCE_PATH: 'datasets/metadata/paco_clip_RN50_a+cname.npy'
    IGNORE_ZERO_CATS_GROUP: [False, False]
    USE_FED_LOSS_GROUP: [True, True]
    CAT_FREQ_PATH_GROUP: [
      'datasets/metadata/lvis_v1_train_cat_info.json',
      'datasets/metadata/paco_lvis_v1_train_cat_info.json',
    ]
DATASETS:
  TRAIN: ("lvis_v1_train", "paco_lvis_v1_train")
  TEST: ("paco_lvis_v1_val",)
SOLVER:
  IMS_PER_BATCH: 16
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005
  STEPS: (300000, 340000)
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 10000
TEST:
  DETECTIONS_PER_IMAGE: 300
  EVAL_PERIOD: 50000
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (640, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [2, 1]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 2]
  USE_RFS: [True, True]
  DATASET_MIN_SIZES: [[640, 800], [640, 800]]
  DATASET_MAX_SIZES: [1333, 1333]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'box']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True